### ISSUE TITLE
Add an option to always have search display in bags

### ISSUE THREAD

**Issue by Cidan** [Cidan/BetterBags#120]
Not sure where to put the search bar yet, but add this as people really miss it.

**Comment by karpana** [comment]
I followed the recommendation to switch over to BetterBags (from Adibags), and was dismayed to find that there was no longer a search feature.  Absolute non-starter for me.

I'm perfectly willing to switch to the new product, but the search feature is an absolute must.

Following this issue, so I can keep track of its resolution/implementation, so that I can switch to this new product.
