### ISSUE TITLE
Quiver not separated from free space

### ISSUE THREAD

**Issue by Danwic90** [Cidan/BetterBags#159]
### Addon Version

v0.1.6

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

![image](https://github.com/Cidan/BetterBags/assets/160560844/f4554351-c6e3-49ab-84c6-d6ef727f91f2)
Quiver empty space is combined with bag empty space

### Steps to reproduce

Quiver in bag slot

**Comment by Silun** [comment]
I want to point out that this is not only a cosmetic issue, but it does have serious impacts:
- You can not always split stacks correctly when there is a free slot in the ammo bag, as the free slot where you put the item might be in the ammo bag. Moving quiver to the right does not always work, see screenshots.
- You can not see how many stacks of ammo you need to buy, because there is no indication of how many free slots the quiver has.

It would be nice if this could get a slight bump in priority, as this issue is not merely cosmetic.

![Image](https://github.com/Cidan/BetterBags/assets/17919060/18a93042-00dc-4cc5-96d9-0c3bda85ad65)



![Image](https://github.com/Cidan/BetterBags/assets/17919060/e54f1b52-7d14-4884-8d2d-1a009d720cca)
