### ISSUE TITLE
Masque Error

### ISSUE THREAD

**Issue by Jaidy88** [Cidan/BetterBags#162]
### Addon Version

v01.1.6

### World of Warcraft Version

Retail

### Describe the bug

Unfortunately, Masque does not work together with Better Bags, all items are black.

### Steps to reproduce

If I switch off Masque, all items look normal

**Comment by Jaidy88** [comment]
https://i.gyazo.com/d58606c966c24781ae007e97b7a733d2.png

**Comment by Cidan** [comment]
Which Masque skin is this?

**Comment by Jaidy88** [comment]
Aaron or Darion both doesnt work

**Comment by Jaidy88** [comment]
both masque skins work with adibags

**Comment by Cidan** [comment]
Alright, let me see if I can figure it out -- there might be a layer error here, but I'm not sure. Sit tight.

**Comment by Cidan** [comment]
Okay, I managed to fix this -- it looks like some Masque skins aren't properly setting the blend mode, which is required for new versions. AdiBags would overwrite the blend mode, where as BetterBags correctly doesn't. For now, I'll overwrite the blend mode manually -- later, I'm going to add this as a hackfix toggle, since it is a hack for a broken masque skin.

I'll release the fix sometime tomorrow.
