### ISSUE TITLE
[Feature]: stationary groups

### ISSUE THREAD

**Issue by Superfly344** [Cidan/BetterBags#257]
### Describe the feature

I love the concept that adibags did and that you're continuing doing, however, the group constantly moving locations during selling or equiping/using makes it annoying to rehunt down the item. Is there anyway to set up the window to be a certain size and then have the groups stay in the locations while bag is open, or even constant would be nice. appreciate your time :).

### Describe the implementation

just an option for static group location in the bags.

**Comment by Cidan** [comment]
Right now, groups and items do not shift if you sell them, but shift if you buy or do a 1:1 swap. There's no real way to keep sections and windows static physically, because as items are put in the bag, they have to go somewhere -- this means I need to make room to draw them.

You should not be seeing items shift when selling items. Can you confirm this behavior?

**Comment by Superfly344** [comment]
you are correct about the items not shifting during selling, i apologize, and the items needing a place to go makes sense, is there a way to prioritize in which order the sections appear than? as well as a way to remove the "new items" section?

ty again for your time :)

**Comment by Cidan** [comment]
That's actually coming soon! It's already planned work. Stay tuned for a future release :)
