### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by Sartrax** [Cidan/BetterBags#263]
### Describe the feature

Make it not autosort upon selling/opening clams etc.

### Describe the implementation

Can we get this option? It makes it hard to sell items

**Comment by theela** [comment]
I have a similar problem. I haven't used any other bag addon since Adibags (and  BetterBags currently), but the constant sorting of items makes it difficult for me to use it.

When selling the items in the bag to the vendor or transferring them to the bank, there should be a way to prevent them from bouncing around due to auto sorting. When I right click on an item, other items move around, which may cause wrong clicks.

And my bag size always changes automatically, no matter how many columns or rows I set it to. It would be nice if there were options for dynamic and static

**Comment by Sartrax** [comment]
Yes it seems whenever I want to sell multiple items, they rearrange making
it easy to misclick and sell other items by mistake. If the layout could
stay the same and just leave an empty slot after selling an item that would
be great (until windows is closed).

Den lör 2 mars 2024 kl 08:10 skrev Antonio Lobato ***@***.***
