### ISSUE TITLE
[Feature]: Sort section in column first

### ISSUE THREAD

**Issue by dzehme** [Cidan/BetterBags#342]
### Describe the feature

I have set my bag to 4 items per row and 3 sections per row.   This is to simulate more what I had with AdiBags.

I feel that the resulting sorting is strange.  I would like the sections to be sorted down a column before moving to the next column.  Instead it seems to be sorted across.  However, if some sections span more than one row, this results in what looks like broken sorting.  For instance, you don't see Gear: Prot next to Gear: Ret.   Fishing and Mining are higher than Consumable - Other.  I find myself having a hard time finding the sections that I am looking for.   This with chromatic sorting taking precedence over alphabetic (covered in another issue), makes it really hard to find the item I am looking for.

![image](https://github.com/Cidan/BetterBags/assets/3292363/bc165448-0653-4867-b88e-f9b260fdc6c0)

### Describe the implementation

I would like an option for sections to sort down columns first.

**Comment by zeptognome** [comment]
Huge +1 on this.
Many (most?) humans read in straight lines, having an alphabetical list of sections not align either horizontally or vertically makes finding smaller sections a much more intensive and slower task.

**Comment by PirateKain** [comment]
MG - I was thinking the same thing. I was going to suggest that here but saw this post so I'll just add my two cents here then.

I hate that the bag always rearranges itself every time an item is added or removed. I use a sorting bag to easily find my stuff, but the auto rearrange keeps moving everything and I still can not easily find my stuff. Defeats the point in the addon being easy to find things.

I would love to be able to arrange them myself and have them never auto rearrange. BEST OPTION!

But yes, if the auto rearrange would go down first then move to the next column and so on, that would be the best alternative to the one I prefer "Self Arrange instead of auto arrange".

Thank you

**Comment by AMaribo** [comment]
This was implemented back in May.
