### ISSUE TITLE
Script to open bag isn't opening up betterbags.

### ISSUE THREAD

**Issue by ozoxchris** [Cidan/BetterBags#36]
I typically run a macro to open my bags via the addon OPie. 
It works with adibags, bagnon, ark inventory but not with betterbags.
Any idea why this isn't working?
Here is the script.
/script ToggleBag(0);

![image_2023-11-29_182002298](https://github.com/Cidan/BetterBags/assets/27544118/1e3e048f-33d4-43b3-a68b-3efa525c2f38)
![image](https://github.com/Cidan/BetterBags/assets/27544118/ebdda631-6624-478d-8259-e2e00624b224)

**Comment by Cidan** [comment]
Try using Open All Bags instead.

**Comment by Cidan** [comment]
Sorry, to be more clear: ToggleAllBags() works. We do this because the open and close bag events are very inconsistent in their behavior and lead to situations where one event chains to another, leaving the game client in an inconsistent state. I could spend a good chunk of time hacking around this, but I find it easier to just bind to ToggleAllBags() and move on. I might revisit this later on though!
