### ISSUE TITLE
Bring back the Item Compaction "None" and Columns Please

### ISSUE THREAD

**Issue by PirateKain** [Cidan/BetterBags#425]
Item Compaction "None" and Display "Columns Sidebar"

Having the rows go down alphabetically instead of to the right was the best part of the addon.

This last update seems to have removed one of the best features of this addon.

Can you please add that back, thank you.

### Describe the implementation

The same way it was before this last update today.

**Comment by Cidan** [comment]
this is back in the latest alpha, with a release later tonight.On Jun 22, 2024, at 08:55, PirateKain ***@***.***> wrote:﻿
Describe the feature
Having the rows go down alphabetically instead of to the right was the best part of the addon.
This last update seems to have removed one of the best features of this addon.
Can you please add that back, thank you.
Describe the implementation
The same way it was before this last update today.

**Comment by AMaribo** [comment]
Columns have been re-added.
