### ISSUE TITLE
Bag/Bank Anchor

### ISSUE THREAD

**Issue by twilite69** [Cidan/BetterBags#466]
### Describe the feature

It would be really awesome to have the bag and bank windows to have an anchor point. This would be especially helpful with the bag when it resorts and part of the bag is offscreen.

### Describe the implementation

You could implement this feature how AdiBags did it with an anchor frame or in the options window by setting a point of the bag/bank window to grow from. Such as Bottom Right for the bag window and/or Top Left for the bank window.

Thanks

**Comment by xathian** [comment]
Yeah it currently seems to anchor from the bottom left, so if you swap between windows that are vastly different in size (like say, your bank and then your reagant tab) the bag shrinks downward

**Comment by Soromeister** [comment]
Any ETA on this? It's one of the features that are driving me insane whenever I use BetterBags. Anchor of bags should be user configurable or at least make it to the bottom right, where the bags usually open. For bank, it should be on the bottom left.

**Comment by glassleo** [comment]
I think this feature not existing is the main pain point for moving on from AdiBags.

Also number of columns should increase if your screen cannot fit more vertically.

**Comment by fireboy92k** [comment]
I agree this is a major pain point for me from AdiBags.  Same issue with the 'Show Bags' option that resets the UI to a different location.  Makes the add on practically unusable for me.

**Comment by GamerMom201** [comment]
This is a feature I would love to see! The bags seem to want to stay on the bottom if it is a different size. Switching between bank tabs can get frustrating, and trying to see the actual bags to swap out bigger ones makes it either take up the whole screen or go off the screen.

**Comment by Cidan** [comment]
this is definitely coming, just wrapping up some other stuff first.

**Comment by Basaingeal** [comment]
I've been playing with the anchors that were just added. They're nice.

It would be nice to be able to choose the growth direction though. I have my anchor in the bottom right quadrant of my screen, but I would like the bag to grow left and down from there. Instead, it will only grow left and up.

Because there's UI/UX in the top of the bag, I like to know where that will be every time, but with my bag anchor towards the bottom right of the screen, I can't do that.

![image](https://github.com/user-attachments/assets/ae343916-58d3-4334-be3c-8a97c9e5b9a9)

**Comment by Cidan** [comment]
> It would be nice to be able to choose the growth direction though. I have my anchor in the bottom right quadrant of my screen, but I would like the bag to grow left and down from there. Instead, it will only grow left and up.

If you anchor to the bottom right, but grow left and down, you violate the constraint of the bottom right (key being bottom) being anchored.

I think what you really want here is to be able to set the anchor point to any of the four corners manually, instead of automating it. In this case, you probably would want the anchor to be on the top right, which would anchor the title to your Details window, but grow down and left.

Someone else asked for something similar -- this shouldn't be too hard to do. I'll add it soon :)

**Comment by Cidan** [comment]
You can now set a manual anchor point in the latest alpha, with a release coming tomorrow.
