### ISSUE TITLE
BugSack error: "Attempted to add item 164254 to category Openable, but the item does not exist."

### ISSUE THREAD

**Issue by devsfan1830** [Cidan/BetterBags#607]
### Addon Version

v0.2.1

### World of Warcraft Version

Retail

### Describe the bug

On load, bugsack logs:

```
1x BetterBags/data/categories.lua:140: Attempted to add item 164254 to category Openable, but the item does not exist.
[string "=[C]"]: in function `assert'
[string "@BetterBags/data/categories.lua"]:140: in function `AddItemToCategory'
[string "@betterbags-openable/Core.lua"]:23: in main chunk

Locals:
(*temporary) = nil
(*temporary) = "Attempted to add item 164254 to category Openable, but the item does not exist."

```

### Steps to reproduce

Loading the game, happens on initial load. Unsure what the item it is referencing is. Plugin seems to otherwise work. I have attached a screenshot of my current bag contents in case that helps.
![World of Warcraft 8_18_2024 2_08_36 PM](https://github.com/user-attachments/assets/85934484-2cba-4574-88a4-ea0d0e9048dd)

**Comment by AMaribo** [comment]
This error is likely caused by a plugin for BetterBags trying to add an invalid item to a category. From the name of the category, it seems like it's probably the [BetterBags - Openable plugin](https://www.curseforge.com/wow/addons/betterbags-openable/commentsl), and checking the comments, someone else is reporting the error as well.
You'll need to reach out to the creator of that plugin with the error to let them fix it.
