### ISSUE TITLE
Changing Itemset highlights last itemset as "recent"

### ISSUE THREAD

**Issue by Kitohub444** [Cidan/BetterBags#686]
### Addon Version

11.02

### World of Warcraft Version

Retail

### Describe the bug

Bags seem not to remember itemsets i already had in bag before when i change them. 

### Steps to reproduce

1. make 2 itemsets
2. change itemset

**Comment by AMaribo** [comment]
When you say change itemset, are you referring to equipping a different set of items?
If so, this is intended behaviour when you have the `All Incoming Items are Recent` checkbox enabled in settings. To remove the gear from recent and place it into the correct category, right-click the bag icon in the top-left corner of the bag.

**Comment by phuze** [comment]
> If so, this is intended behaviour when you have the All Incoming Items are Recent checkbox enabled in settings. To remove the gear from recent and place it into the correct category, right-click the bag icon in the top-left corner of the bag.

This behavior is odd, as items that are swapped when changing gear sets, are not new items to a player, and should not appear as such. The default setting should be [reverted back to disabled/false](https://github.com/Cidan/BetterBags/commit/358504b39c8b62278264eaaf302f496614d01a21).

**Comment by Cidan** [comment]
This will not be changed. The problem here is, when swapping items, the entire bag has to be redrawn if we were to put them in the correct section, which is in itself a big problem. To further complicate things, Blizzard doesn't expose a mechanism for detecting when equipment is swapped versus when you pick up an item, making it tricky to tell when an item is actually from equipment.
