### ISSUE TITLE
LUA error / Disable Addon 

### ISSUE THREAD

**Issue by Sk-wessel** [Cidan/BetterBags#76]
When searching through the Dungeon Journal, whilst the bag is open. 
The game prompts me to disable the add-on, if i don't the game blocks key inputs. 

![billede](https://github.com/Cidan/BetterBags/assets/93919172/f9e1afb0-8ae7-4b4b-a532-ac5745229d6a)

( 4x [ADDON_ACTION_FORBIDDEN] AddOn 'BetterBags' tried to call the protected function 'OnOpen()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `OnOpen'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:586: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:575>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2938: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2781: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2646: in function <FrameXML/UIParent.lua:2642>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3248: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:3209: in function `ToggleFrame'
[string "@FrameXML/UIParent.lua"]:1143: in function `ToggleEncounterJournal'
[string "TOGGLEENCOUNTERJOURNAL"]:1: in function <[string "TOGGLEENCOUNTERJOURNAL"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
} )

**Comment by fubbleskag** [comment]
does this happen every time you open the dungeon journal or only when you navigate to or search for specific things?

(for anyone else trying to replicate, this is in the dungeons tab of the adventure guide)

**Comment by banjoman05** [comment]
Had to disable the addon. Sometime recently I've started getting the above "blocked from an action" and it's always Better Bags being "blocked". Happens especially right after zoning in, taking a portal, etc... Blocks me from using mouse button keys, or number row keys until I disable the addon or /reload (after which everything works fine for a while, maybe until next relog/rezone).

**Comment by Cidan** [comment]
I know this says BetterBags in the error, but this isn't being caused by BetterBags.

Addons in WoW all share a single large namespace and co-mingle the execution environment. This means that if, for example, the Ace library is loaded by 20 addons, only 1 copy of Ace is loaded into memory, and whichever copy is loaded is picked at semi-random based on your installs. If another addon "taints" Ace in some way, the addon responsible for holding Ace in memory gets blamed, even though it didn't cause the issue.

In this case, `Blizzard_EncounterJournal` is in the execution path, which BetterBags does not touch or use in any way whatsoever. Furthermore, `OnOpen` is the function that is being called while tainted -- if you search through BetterBags code, `OnOpen` doesn't even exist.

Generally speaking, when you get a taint error, you need to disable all your addons, enable the one that's blamed (along with buggrabber/bugcatcher) and try to reproduce it. If you can't, start enabling your addons one-by-one until the taint happens, and you'll have found your culprit.

Thanks.
