### ISSUE TITLE
Pawn Upgrade Icon

### ISSUE THREAD

**Issue by MichaelPriebe** [Cidan/BetterBags#78]
Would love to see support for showing the Pawn upgrade icon.

**Comment by radhaz** [comment]
Just made an alt and enabled Pawn and I am not seeing the typical arrow notification on the tooltip while using BetterBags; however, the arrow is present in Adibags? I see the issue is marked complete so I'm wondering if it is my side/settings? Should I open a new issue since this is marked as completed?

BetterBags v.0.1.7
Pawn 2.8.9

**Comment by Cidan** [comment]
Complete, not released. When this issue closes, it will be released.
