### ISSUE TITLE
[Feature request] Add clamping to bag UI and optimize bank sort display

### ISSUE THREAD

**Issue by Rycia** [Cidan/BetterBags#99]
Currently, the bag can fall off the screen, like so:
![image](https://github.com/Cidan/BetterBags/assets/43384589/62f7ed1d-8872-41bb-b400-aadb4c034548)
Would be nice to make it so that this doesn't happen by adding clamping.

The bank does the same thing and falls off the screen, especially with a lot of stuff; but this is probably an issue with how the addon formulates the most effective way to sort out sections to preserve space.
Here's an example of that. Viewing in anything but single bag view is almost impossible with a full bank at times.
![image](https://github.com/Cidan/BetterBags/assets/43384589/b8912a3d-337f-4f3d-950b-c0cc0a04d66e)
![image](https://github.com/Cidan/BetterBags/assets/43384589/67974cea-c5de-4fcf-a75f-0e7dd35967c0)
Sections like free slots, armor, junk, keys, known BoP, reagent, unknown - rogue, and weapon, can easily be stacked to make this window A LOT smaller. So optimizations can really be done here.

With specific items, a bank can easily fall off the screen.

**Comment by Cidan** [comment]
A lot of work has gone into this, and this doesn't quite work as you expect with large windows. The window is actually clamped already, but at a rect around the bag button, meaning only the bag button is clamped to screen. This is intentional, as the bag button (as you have noticed) can easily grow to be out of bounds. This is particularly true on players at lower resolutions or with smaller monitors.

Your second screenshot is a bit contrived in nature, and it is known this will cause issues. This is why the default bag parameters prevent that kind of layout, and why clamping prioritizes the bag button so that options can be changed and the bag fixed.

Ultimately, category grouping is deterministic and will remain so. We will not do bin packing to sort items closer together based on the size of the section at any point, as this was a chief complaint of AdiBags.

Thanks/
